import { jsPDF } from 'jspdf';
import { LeadApplication } from '../types';

export function generateApplicationPDF(application: LeadApplication): Blob {
  const doc = new jsPDF();
  const a = application.applicant;
  
  // Header
  doc.setFontSize(20);
  doc.text('Heritage Housing - Credit Application', 20, 20);
  
  doc.setFontSize(10);
  doc.text(`Application ID: ${application.id}`, 20, 30);
  doc.text(`Submitted: ${new Date(application.submittedAt).toLocaleString()}`, 20, 35);
  
  // Personal Information
  doc.setFontSize(14);
  doc.text('Personal Information', 20, 45);
  
  doc.setFontSize(10);
  let y = 55;
  
  if (a) {
    doc.text(`Name: ${a.firstName || ''} ${a.lastName || ''}`, 20, y); y += 7;
    doc.text(`Email: ${a.email || ''}`, 20, y); y += 7;
    doc.text(`Phone: ${a.phone || ''}`, 20, y); y += 7;
    doc.text(`Date of Birth: ${a.dateOfBirth || ''}`, 20, y); y += 7;
    doc.text(`SSN: ${a.ssn || ''}`, 20, y); y += 7;
    doc.text(`Address: ${a.address || ''}`, 20, y); y += 7;
    doc.text(`City: ${a.city || ''}, State: ${a.state || ''} ${a.zipCode || ''}`, 20, y); y += 7;
    doc.text(`Time at Address: ${a.timeAtAddress || ''}`, 20, y); y += 7;
    doc.text(`Monthly Income: $${a.monthlyIncome || ''}`, 20, y); y += 7;
    doc.text(`Employment Status: ${a.employmentStatus || ''}`, 20, y); y += 7;
    doc.text(`Employer: ${a.employer || ''}`, 20, y); y += 7;
    doc.text(`Job Title: ${a.jobTitle || ''}`, 20, y); y += 7;
    doc.text(`Time at Job: ${a.timeAtJob || ''}`, 20, y); y += 7;
  }
  
  // Housing Preferences
  y += 10;
  doc.setFontSize(14);
  doc.text('Housing Preferences', 20, y); y += 10;
  
  doc.setFontSize(10);
  if (a) {
    doc.text(`Land Status: ${a.landStatus || ''}`, 20, y); y += 7;
    doc.text(`Land Location: ${a.landLocation || ''}`, 20, y); y += 7;
    doc.text(`Bedrooms Needed: ${a.bedrooms || ''}`, 20, y); y += 7;
    doc.text(`Utilities Needed: ${a.utilities || ''}`, 20, y); y += 7;
    doc.text(`Credit Estimate: ${a.creditEstimate || ''}`, 20, y); y += 7;
    doc.text(`Repo History: ${a.repoHistory || ''}`, 20, y); y += 7;
  }
  
  // Appointment
  if (application.appointmentDate) {
    y += 10;
    doc.setFontSize(14);
    doc.text('Appointment Scheduled', 20, y); y += 10;
    doc.setFontSize(10);
    doc.text(`Date: ${new Date(application.appointmentDate).toLocaleString()}`, 20, y); y += 7;
  }
  
  // Documents
  if (application.documents && application.documents.length > 0) {
    y += 10;
    doc.setFontSize(14);
    doc.text('Documents Uploaded', 20, y); y += 10;
    doc.setFontSize(10);
    application.documents.forEach((doc, i) => {
      doc.text(`${i + 1}. ${doc.type}: ${doc.name}`, 20, y); y += 7;
    });
  }
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by Heritage Housing Application System', 20, 280);
  
  return doc.output('blob');
}
